import type { ConceptId, Question } from '../schema'

/**
 * One loader per concept, so a check downloads that concept's questions and nothing else
 * (09-QUESTION-BANK §4.2). The initial bundle contains no questions at all, which is what
 * M10 has to ship.
 *
 * A pool is its authored questions followed by the frozen derived ones. `derived.json` is
 * generated by `npm run generate` and committed, never hand-edited: an edit there is lost on
 * the next run (CLAUDE.md).
 */
const LOADERS: Readonly<Record<ConceptId, () => Promise<readonly Question[]>>> = {
  'capacity-and-utilization': async () => {
    const [authored, derived] = await Promise.all([
      import('./capacity-and-utilization/authored'),
      import('./capacity-and-utilization/derived.json'),
    ])
    return [...authored.capacityAndUtilizationAuthored, ...(derived.default as unknown as readonly Question[])]
  },
  percentiles: async () => (await import('./percentiles/authored')).percentilesAuthored,
}

export async function loadQuestions(conceptId: ConceptId): Promise<readonly Question[]> {
  const pool = await LOADERS[conceptId]()
  // In dev only, so authoring mistakes surface as you write them. Production trusts the
  // validator, which runs in CI and in the definition of done (ADR-0042).
  if (import.meta.env.DEV) {
    const { QuestionSchema, parseContent } = await import('../parse')
    const problems = pool.flatMap((question) => parseContent(QuestionSchema, question, `questions/${conceptId}`))
    if (problems.length > 0) throw new Error(problems.map((problem) => problem.message).join('\n'))
  }
  return pool
}
